name: Build, Deploy, and Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name (e.g., v1.0.1)'
        required: true
        default: 'v1.0.1'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with Eleventy
        run: npm run build

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Create ZIP archive
        run: |
          cd _site
          zip -r ../stroi.etos.ru-v${{ github.event.inputs.tag_name || github.ref_name }}.zip . -x "*.git*"
          cd ..

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
          release_name: Release ${{ github.event.inputs.tag_name || github.ref_name }}
          body: |
            Релиз сайта "ЭТОС" (stroi.etos.ru).
            Скачайте `stroi.etos.ru-v${{ github.event.inputs.tag_name || github.ref_name }}.zip` для статической версии сайта.
          draft: false
          prerelease: false

      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./stroi.etos.ru-v${{ github.event.inputs.tag_name || github.ref_name }}.zip
          asset_name: stroi.etos.ru-v${{ github.event.inputs.tag_name || github.ref_name }}.zip
          asset_content_type: application/zip